### PR TITLE
Default DB Configuration

### PR DESCRIPTION
**Pull request by peter-fritchley**
Added an array of default DB configuration, to avoid the issue in #13

### CODE REVIEW

**Comment by thomasjthomasj** [comment]
Hi Peter,

Welcome to Mothership, and thanks a lot for trying out the platform and submitting your fix. I won't get the chance to look at it properly until Monday, but I need to know, did running the installer with this change solve your issue, to the point that you were able to access the admin panel in your browser?

I have a feeling that thereis a deeper issue at play here, and the array should have been loaded from a yaml file that would have been generated when Composer was run. If you chck your config directory, is it full of other config files? Did the installer ask for your general site details?

We will need to investigate the root cause of the issue before we canerge your fix, as it might make more sense to throw an exception (see https://github.com/mothership-ec/mothership-install/pull/8 which adds a lot more validation and will be merged next week)

**Comment by peter-fritchley** [comment]
Hi Thomas, 

I think your right - I had to manually copy the composer file and run composer install, then manually run the DB migrations before being able to access the admin.

I've run the installer on another machine now and everything seems to be working fine.

Thanks

**Comment by thomasjthomasj** [comment]
Ok great, glad you were able to get it sorted! I'll close the issue, feel free to re-open it if you feel it still neess addressing :)

**Comment by thomasjthomasj** [comment]
Also if you need help getting started with the platform, be sure to check our wiki at http://wiki.mothership.ec, although it's still quite light on documentation, so asking at http://forum.mothership.ec might be a good bet too

**Pull request closed without merging**
